---
title: 'R Programming Assignment 2: Lexical Scoping'
author: "Juan Neculmán"
date: "06-02-2022"
output: html_document
---

setwd()

Note: I don't know how about the fork/clone, so maybe a do the right. 

#R Programming Assignment 2: Lexical Scoping

#This function creates a special #matrix that stores its inveres

```{r}
makeCacheMatrix <- function(x = matrix()) {
  #Initialize the inverse property
  j <- NULL
  #Set the matrix
  set <- function(y){
  x <<- y
  j <<- NULL
  }
  #Get the matrix
  get <- function()x
  #Method to set the inverse of the matrix
  setInverse <- function(inverse) j <<- inverse
  #Method to get the inverse of the matrix
  getInverse <- function() j 
  # Return list
  list(set = set, get = get, 
  setInverse = setInverse, 
  getInverse = getInverse)
}
```


```{r}
cacheSolve <- function(x, ...) {
## So, here return a matrix that is the inverse of 'x'
  j <- x$getInverse()
  if(!is.null(j)){
  message("getting cached data")
  return(j)
  }
  #Get the matrix from the objects
  mat <- x$get()
  #Calculate
  j <- solve(mat,...)
  x$setInverse(j)
  #Return the Matrix
  j
}
```

